IL-378 Remove KUBERNETES_* vars to fix `kubectl` errors
hashicorp/field-workshops-consul pull request #187
Opened 2022-06-27 18:08 UTC by thomashashi

When both KUBERNETES_* vars are set and
/run/secrets/kubernetes.io/serviceaccount/namspace exist `kubectl`
assumes you want to run it using the pod's ServiceAccount
credentials and in the namespace the pod is running. We don't want
to do that, we want to explicitly use the credentials and setup
in ~/.kube/config, so delete the environment variables (we cannot
remove the /run/secrets/... file because it's mounted readonly,
and Instruqt doesn't give us the option to not have those mounted
in)

Fixes https://hashicorp.atlassian.net/browse/IL-378

2022-06-27 18:20 UTC, omkensey commented
LGTM

2022-06-29 21:19 UTC, ramramhariram requested changes
@thomashashi - i tested the fix by going through the track, so looks like setup script worked. But i also see this update to the solve script for challenge 9 that seems different than the setup cloud client file, is this leftover and needs to be either updated to match or be removed? Please update as you see fit and let us know.

2022-06-29 21:24 UTC, thomashashi commented
@[ramramhariram](https://github.com/ramramhariram) they are different, because in [track_scripts/setup-cloud-client](https://github.com/hashicorp/field-workshops-consul/pull/187/files#diff-d758c9771daf310244c92696ccbfe41a37b0ed222e563f3588ab6e60cfda2b6e) we want to *echo* that command into the `.bashrc`, but in [09-provision-gcp-consul-secondary-datacenter/solve-cloud-client](https://github.com/hashicorp/field-workshops-consul/pull/187/files#diff-e8b6e3ce6ebe4487e3259ee04652d9af3aaf3490f90ab579e46217501e18987b) we actually want to *run* that command right there in the solve script.

2022-06-29 21:55 UTC, ramramhariram approved these changes
Approved per testing with TK's track and noted comments in this PR

2022-06-30 13:20 UTC, merged